config/routes.rb
CloudRadio::Application.routes.draw do
  
  resources :songs do
    member do
      get 'like'
      get 'unlike'
    end
  end
  get '/home' => 'users#home'
  get '/homepage' => 'users#homepage'
  get 'users/recently' => 'users#recently'
  get 'users/songsliked' => 'users#songsliked'
  get 'users/reset' => 'users#reset'
  get '/users/userlib' => 'users#userlib'
  get '/users/edit' => 'users#edit'
  get '/users/about' => 'users#about'
  devise_for :users
  #root to: 'users#home'
  root to: 'static_pages#home'
end

app/models/user.rb
# User Class should have a commit
class User < ActiveRecord::Base
	has_many :songs
	make_flagger
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  serialize :genre, Hash
  serialize :disliked, Hash



  def self.calculate_genre (user, client)
		# init some parameters
		track_id = []
		#id_array = user.get_id_array(user)
		sum = user[:genre].values.sum
		array = []
		# Handle the user preference
		if sum != 0 && sum <= 100
			user[:genre].each do |genre|
				track_id += user.get_track(genre[1], genre[0], client, user)
			end
		end

		if track_id.size < 100
			size_count = 100 - track_id.size
			size_count.times do
				array << rand(1..2400)
			end
			track_finds = Track.find(array)
			track_finds.each do |track_find|
				if track_find.duration < 500000 && user.disliked[track_find.track_id] != true
					track_id << track_find.track_id
				end
			end
		end

		# End handle and Prepare for output
		track_sound = user.get_track_handled(track_id, client)
    track_genre = Track.find_by_track_id(track_sound["id"].to_s)["genre"]

    # get embed information
    track_url = track_sound['permalink_url']
    embed_info = client.get('/oembed', :url => track_url)
    embed_http = embed_info['html'].split("src=\"")[1].split("\">")[0]
    # The return value
    [track_sound, track_genre, embed_http]
	end

	# this method will return a series of track id within an array for certain genre
	def get_track(count, genre, client, user)
		track_id = []
		array = []
		genre_array = %w(blues classical country electro folk hiphop jazz metal mixtape pop rock rap)
		loc = genre_array.index(genre) + 1

		count.times do
			array << rand(((loc-1)*200+1)..((loc)*200))
		end
		track_find = Track.find(array)
		track_find.each do |track_find|
			if track_find.duration < 500000 && user.disliked[track_find.track_id] != true
				track_id << track_find.track_id
			end
		end
		track_id
	end

	# this method will return a track from soundcloud 
	def get_track_handled(track_id, client)

		track = track_id[rand(0..track_id.size)]
		begin
			track_sound = client.get("/tracks/#{track}")
		rescue
			track_sound = get_track_handled(track_id, client)
		end
		track_sound
	end

	# this method is for non-login user
	def self.get_track_nonlogin(track_id, client)
		begin
			track_sound = client.get("/tracks/#{track_id}")
		rescue
			track_sound = get_track_handled(track_id, client)
		end
		track_sound
	end

	# this method will return array of user song id
	# this is feature envy, just comment it out
	# def get_id_array(user)
	# 	id_array = []
	# 	user.songs.each do |song|
	# 		id_array << song.songid
	# 	end
	# 	id_array
	# end
end

app/controllers/users_controller.rb
# Just a Controller need the description
class UsersController < ApplicationController
  skip_before_action :authenticate_user!,  only: [:home]
  include UsersHelper
  # this is home page for non-login user
  def home
    @client = Soundcloud.new(:client_id => 'ae9f52f98895e6a3663870f4de3549a5')
    track_find = Track.find(rand(1..2400))
    track = User.get_track_nonlogin(track_find.track_id, @client)
    genre = track["genre"]
    track_url = track['permalink_url']
    embed_info = @client.get('/oembed', :url => track_url)
    @embed_http = embed_info['html'].split("src=\"")[1].split("\">")[0]
    @duration = track["duration"] / 1000 + 5
    @song = Song.create(:name => track["title"], :genre => genre, :artist => track["user"]["username"], :songid => track["id"], :duration => @duration, :url =>track['permalink_url'])
    if current_user.present?
      redirect_to homepage_path
    end
  end

  # this main homepage, play songs automaticly
  def homepage
    @client = Soundcloud.new(:client_id => 'ae9f52f98895e6a3663870f4de3549a5')
    track_genre = User.calculate_genre(current_user, @client)
    track = track_genre[0]
    genre = track_genre[1]
    @embed_http = track_genre[2]
    @duration = track["duration"] / 1000 + 5
    @song = Song.create(:name => track["title"], :genre => genre, :artist => track["user"]["username"], :songid => track["id"], :duration => @duration, :url =>track['permalink_url'])
    current_user.songs << @song
    current_user.save
    respond_to do |format|
      format.json { render json: {embed_http: @embed_http, song: @song} }
      format.html
    end
  end

  # user preference page, can change user's preference
  def userlib
    @genre_array = %w(blues classical country electro folk hiphop jazz metal mixtape pop rock rap)
    genre_add = %w(blues classical country electro folk hiphop jazz metal mixtape pop rock rap)
    if current_user.genre.size < 12
      current_user.genre.each do |genre|
        if @genre_array.include?(genre)
          genre_add.delete(genre)
        end
      end
      genre_add.each do |genre|
        current_user.genre[genre] = 0
      end
      current_user.save
    end
  end

  # can edit user's preference using this method
  def edit
    @genre = params[:genre]
    @act = params[:act]
    # use current_user.genre and current_user[:genre].values.sum multiple times
    # so have the DuplicateMethodCall, have already refact it
    current_user_genre = current_user.genre
    user_genre_sum = current_user[:genre].values.sum

    if @act == 'increase'
      if user_genre_sum <= 95
        current_user_genre[@genre] += 5
      elsif user_genre_sum > 95 && user_genre_sum < 100
        current_user_genre[@genre] += 100 - user_genre_sum
      end
      # original one has too many statements, so refact it
    elsif @act == 'decrease' && user_genre_sum >= 5 && current_user_genre[@genre] >= 5
        current_user_genre[@genre] -= 5
    end
    current_user.save
    redirect_to users_userlib_path
  end

  # will show the liked songs from user
  def songsliked
    @songs = current_user.songs
  end

  def about
  end

  def recently
    flag = false
    @songs = current_user.songs
    size = @songs.size
    # the original issue is about @n, this variable is Uncommunicative variable name
    # has change that to number
    @number = params[:n].to_i
    if @number <= (size - size % 5 )
      if @number == (size - size % 5)
        @number += size % 5
      else
        @number += 5
      end
    end
  end

  # reset user preference
  def reset
    current_user.genre.each do |genre|
      current_user.genre[genre[0]] = 0  if current_user.genre[genre[0]].present?
    end
    current_user.save
    redirect_to users_userlib_path
  end

end

app/helpers/users_helper.rb
module UsersHelper

	
end

app/views/users/about.html.erb
<h1 class="about_title">About Cloud Radio</h1><br>
<h4 class="about_content" style="color:red">A smart Radio created by <em style="color:black">Yiyang Song</em>, You can play with it by clicking "Heart" button. The app will store your style and bring more of similar styles next time. Also, you can change your styles manually, it looks coooooool! </h4><br><br>

<p style="color:grey"><em>Contact me if you like it...</em></p>
<h4><em>Name</em>:  Yiyang Song</h4>
<h4><em>Email</em>:  songyiyang2012@gmail.com</h4>
<h4><em>Phone</em>:  352-284-6481</h4>
<h4><em>Address</em>:  101 Main Street, Cambridge, MA </h4>

app/views/users/home.html.erb
<meta http-equiv="Refresh" Content="<%= @duration %>">

<nav class="navbar navbar-inverse" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="#"><span class="glyphicon glyphicon-home"> CloudRadio</span></a>
    </div>
      <ul class="nav navbar-nav navbar-right">
        <li><span class="login">Please <%= link_to 'Log in', homepage_path%> to use the smart radio
					</span>
				</li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="homepage_div">


<div id="one" class="nonlog_frame">
<iframe width="70%" height="350px" scrolling="no" frameborder="no" src="<%= @embed_http %>&auto_play=true" ></iframe>


<div id="five" class="nonlog_song_next"><%= link_to raw("<span class=\"glyphicon glyphicon-forward\">  Next&nbsp </span>"), home_path, class: "btn btn-default btn-lg" %></div>

<div id="six" class="genre">&nbspGenre: <%= @song[:genre] %>&nbsp</div>
</div>
<div class="remider">
@CloudRadio Created by <em>Yiyang Song</em>
</div>
</div>

app/views/users/homepage.html.erb
<nav class="navbar navbar-inverse" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      
      <a class="navbar-brand" href="#"><span class="glyphicon glyphicon-home"> CloudRadio</span></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">

        <li><div class="preference">
          <%= link_to raw("<span class=\"glyphicon glyphicon-cog\"> Preference</span>"), users_userlib_path, :onclick => "window.open(this.href, 'create_company',  'width=800px,height=600px');return false;", class: "btn btn-default btn-md" %>&nbsp &nbsp
          </div>
        </li>

        <li><div class="recently">
          <%= link_to raw("<span class=\"glyphicon glyphicon-music\"> Recent</span>"), users_recently_path(:n => 0), :onclick => "window.open(this.href, 'create_company',  'width=500,height=250');return false;", class: "btn btn-default btn-md"%>&nbsp &nbsp
          </div>
        </li>

        <li><div class="song_liked">
          <%= link_to raw("<span class=\"glyphicon glyphicon-star\"> Favorite</span>"), users_songsliked_path, :onclick => "window.open(this.href, 'create_company',  'width=600,height=400');return false;", class: "btn btn-default btn-md" %>&nbsp
          </div>
        </li>
        <li><div class="about">
          <%= link_to raw("<span class=\"glyphicon glyphicon-cloud\"> About</span>"), users_about_path,
            :onclick => "window.open(this.href, 'create_company', 'width=600, height=400');return false;", class: "btn btn-default btn-md" %> &nbsp
          </div>
        </li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li><div class="signin">Signed in as <%= current_user.email %>  <%=link_to 'sign out?', destroy_user_session_path, method: :delete %>
					</div>
				</li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="homepage_div">

<div id="one" class="frame">
<iframe id="my-iframe" width='60%' height='400' scrolling='no' frameborder='no' src="<%= @embed_http%>&auto_play=true" ></iframe>
</div>

<div class="buttons">
<div id="two" class="like_button">
	<%= toggle_like_button(@song, current_user) %>
	<br><br><br><br>
</div>

<button id="unlike" class="btn btn-default btn-lg", data-song="<%= @song.id %>">
ThrowAway...
</button>

<button id="three" class="btn btn-default btn-lg">Next</button>

<div id="four" class="genre">&nbspGenre: <%= @song[:genre] %>&nbsp</div>
</div>

<div class="remider">
@CloudRadio Created by <em>Yiyang Song</em> for <strong>YY</strong>
</div>
</div>
<div><%= link_to "Refresh", homepage_path %></div>
<!-- <div class="playing">Now playing: <%= @song[:name] %></div> -->







<!-- <div class="artist">Artist: <%= @song[:artist] %></div>
 -->

app/views/users/recently.html.erb
<div class="recent_title">Here shows Recent <%= @number %> songs you've listened </div>

<%= link_to 'See More...', users_recently_path(:n => @number) ,{:style => "color:tomato;"} %>

<div class="recent_content">
<ol>
<% @songs.last(@number).reverse.each do |song| %>
	<li><em class="song_name"><%= song.name %></em>	&nbsp<%= " #{((song.duration - 5) / 60)}' #{((song.duration - 5) % 60 )}'' " %></li>
<% end %>
</ol>
</div>

app/views/users/songsliked.html.erb
<div class="songs_like_title">Your favorite Songs...</div>

<div class="songs_like_content">
<ol>
<% @songs.each do |song| %>
	<% if current_user.flagged?(song) %>
		<li><em class="song_favorite"><%= song.name %></em>&nbsp&nbsp<%= link_to raw("<span class=\"glyphicon glyphicon-headphones\"></span>"), song.url, class: "btn btn-default btn-sm" %></li>
	<% end %>
<% end %>
</ol>
</div>

app/views/users/userlib.html.erb
<div class="userpref_title"><em>Modify your preference...</em><span class="style">Stylized: <%= current_user[:genre].values.sum %> % &nbsp | &nbsp Randomlized: <%= 100 - current_user[:genre].values.sum %> % &nbsp &nbsp</span></div>



<div class="reset?"><strong><%= link_to "Reset?", users_reset_path, :style => "color: tomato; font-size: 16px" %></strong></div>

<div class="change">
<dl style="width: 500px">
<% current_user.genre.each do |genre| %>
<dt><%= genre[0] %></dt>
<dd><div class="bar" style="width: <%= genre[1] %>%;"><%= genre[1] %>%</div></dd>
<% end %>
</dl>

<ul class="change_pref">
<% current_user.genre.each do |genre| %>
	<% @genre = genre[0] %>
	<% if current_user[:genre].values.sum == 100 %>
		 +  |  <%= link_to raw("<span class=\"glyphicon glyphicon-minus\"> </span>") , users_edit_path(current_user.id, :genre => @genre, :act => 'decrease', class: "btn btn-default btn-lg" )%><br><br>

	<% elsif current_user[:genre].values.sum == 0 %>
		<%= link_to raw("<span class=\"glyphicon glyphicon-plus\"> </span>"), users_edit_path(current_user.id, :genre => @genre, :act => 'increase', class: "btn btn-default btn-lg") %>  |  -<br><br>

	<% else %>
		<%= link_to raw("<span class=\"glyphicon glyphicon-plus\"> </span>"), users_edit_path(current_user.id, :genre => @genre, :act => 'increase', class: "btn btn-default btn-lg") %>  |  <%= link_to raw("<span class=\"glyphicon glyphicon-minus\"> </span>") , users_edit_path(current_user.id, :genre => @genre, :act => 'decrease', class: "btn btn-default btn-lg")%><br><br>
	<% end %>
<% end %>
</ul>
</div>